trigger:
  - master

pool:
  name: Default

steps:
  - script: echo Hello, it's my Azure DevOps App
    displayName: 'Run an echo command'

  - script: mvn clean install
    displayName: 'Build with Maven'

  - script: java -jar target/lab2-0.0.1-SNAPSHOT.jar
    displayName: 'Run the JAR file of My Lab2 App'